name: ChangHyeon Nam's Blog
url: 'https://changhyeonnam.github.io'
description: 'notes and thoughts'

exclude: [Gemfile, Gemfile.lock, README.md]

author: 'ChangHyeon Nam'
disqus_shortname: Nam

future: true

kramdown:
  input: GFM
  math_engine: mathjax

# gems:
#   # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
#   - jekyll-gist
#   - jekyll-sitemap

# sitemap:
#     filename: "/sitemap.xml"
#     exclude:
#         - "/atom.xml"
#         - "/feed.xml"
#         - "/feed/index.xml"
#     include_posts:
#         - "/index.html"
#     change_frequency_name: "change_frequency"
#     priority_name: "priority"

sass:
    sass_dir: _sass
    style: :compressed
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-toc
